# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: gradle
      - task: build

  build:
    preconditions:
      - mvn --version
    cmds:
      - cmd: |
          mvn -B verify

  db:
    internal: true
    deps: [stop-db]
    cmds:
      - cmd: |
          docker compose up -d db

  stop-db:
    internal: true
    cmds:
      - cmd: |
          docker compose stop db
        ignore_error: true

  test:
    deps: [db]
    env:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_URL: localhost:5432/postgres
    cmds:
      - cmd: |
          mvn test

  publish:
    cmds:
      - cmd: |
          mvn -DskipTests clean deploy

  format:
    cmds:
      - cmd: |
          npm init -y
        ignore_error: true
      - cmd: |
          npm install prettier@latest
          npm install prettier-plugin-java@latest
      - cmd: >-
          "{{ joinPath .TASKFILE_DIR "node_modules" ".bin" "prettier" }}"
          --single-quote
          --print-width 120
          --plugin=prettier-plugin-java
          --write
          "{{ .TASKFILE_DIR }}"
      - cmd: |
          rm -rf node_modules package.json package-lock.json

  gradle:
    cmds:
      - cmd: git add .
      - cmd: git clean -xfd
      - cmd: >-
          "{{ joinPath .TASKFILE_DIR "gradlew" }}" build
          --no-build-cache
          --dependency-verification=strict
          --refresh-dependencies
          --rerun-tasks
